### ISSUE TITLE
Unable to connect to the application using the QR Code

### ISSUE THREAD

**Issue by DiegoBM** [react-community/create-react-native-app#172]
Hi All
I'm having an issue while trying to run my application. I've created the project normally with create-react-native app. I run the npm start command with "REACT_NATIVE_PACKAGER_HOSTNAME" assigning a valid ip address since it initially finds my virtualbox ip, but still my android device cannot connect to that ip address using the QR code, even though they are both in the same network. with a java.net.ConnectException. failed to connect to /192.168.0.20:19000.

My system is a Surface Book with Windows 10 Pro, and the only thing that I can think of is either firewall, antivirus (Kaspersky Internet Security), or that I'm running inside a mac-address-restricted wi-fi network. Does this ring any bells?

I don't know if it's worth mentioning that the npm start outputs these lines at some point:

`Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
`

After that it seems to complete without problems, prints ip, port and QR, but I cannot connect to it.

Thank you in advance

**Comment by dikaiosune** [comment]
Hi! Sorry to hear that you're having issues. Please check the network troubleshooting section of the User Guide and try the steps there. Also, the issue template includes very important information for being able to help with your issue. Unfortunately I don't have the resources right now to help with issues don't include that information.

**Comment by DiegoBM** [comment]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Created a single application by running create-react-native-app. When finished the automatic process I did run 
REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.20 npm start

The automatic process started with no abormal messages beyond:

`Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...

'yarn' is not recognized as an internal or external command,
operable program or batch file.
`

At the end I can see a huge QR code and a message stating:
`Or enter this address in the Expo app's search bar:

  exp://192.168.0.20:19000
`
Finally I opened Expo in my mobile device and tried to scan the QR code

## Expected Behavior

I was expecting to see the application on my mobile device after scanning the QR Code

## Observed Behavior

A blue screen was presented stating:
Something went wrong.
Could not load exp://192.168.0.20:19000

After pressing "View error log" I can see:
Uncaught Error: java.net.ConnectException: Failed to connect to /192.168.0.20:19000
Time: 6:51:28 Fatal Error

No errors or messages at all in the terminal

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.27
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: v7.9.0
* `npm -v`: 4.2.0
* `yarn --version`: --
* `watchman version`: --

Also specify:

1. Operating system: Windows 10 Professional - Creators Update
2. Phone/emulator/simulator & version: Google Nexus 5. Android 5.1.1

Expo Client version: 1.15.0 

## Reproducible Demo

Not sure what to fill in here

**Comment by dikaiosune** [comment]
OK, it looks like there are two things here:

1. The yarn error message is a bug that has been fixed upstream but which should not affect running the program. I expect the bugfix to be available in the next few days.
2. Are you able to reach the dev server's URL in your phone's web browser? This step is documented in the network troubleshooting section of the user guide. If you're not able to reach the URL in your phone's browser, then there's probably something on your local network preventing you from reaching your dev machine at all. Note that you don't need to run CRNA inside a container, it will run natively on Windows. Also, if you're continuing to have issues you may want to try installing [Expo XDE](https://docs.expo.io/versions/v16.0.0/introduction/installation.html) which will create network tunnels for you.

**Comment by DiegoBM** [comment]
I just tried accessing http://192.168.0.20:19000 and http://192.168.0.20:19001 in my phone browser. In both cases I can see a message "This site can't be reached".

It's worth noting that I used to have Expo XDE installed but I did uninstall it since Kaspersky Internet Security 2017 was reporting one of it's elements as damaging

**Comment by DiegoBM** [comment]
Disabling the mac-address access control doesn't solve the issue, so it's not the mac-limitation
