### ISSUE TITLE
couldn't start new project

### ISSUE THREAD

**Issue by jesicasaussay** [react-community/create-react-native-app#236]
## Description

I created a new project with
$ npm i -g create-react-native-app
$ create-react-native-app my-project
but I'm getting an error when I run npm start

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
> my-project@0.1.0 start /Users/jesicagreenwell/my-project
> react-native-scripts start

17:58:58: Starting packager...
17:59:03: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1039:11
    at Generator.next (<anonymous>)
    at step (/Users/jesicagreenwell/my-project/node_modules/xdl/build/Project.js:1461:191)
    at /Users/jesicagreenwell/my-project/node_modules/xdl/build/Project.js:1461:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jesicagreenwell/.npm/_logs/2017-06-03T07_59_03_045Z-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.30

* `npm ls react-native`: └── UNMET DEPENDENCY react-native@^0.44.0
npm ERR! missing: react-native@^0.44.0, required by my-project@0.1.0

* `npm ls expo`:
└── UNMET DEPENDENCY expo@^17.0.0
npm ERR! missing: expo@^17.0.0, required by my-project@0.1.0

* `node -v`: v8.0.0
* `npm -v`: 5.0.1
* `yarn --version`: 0.24.5
* `watchman version`: {"version": "4.7.0"}

Also specify:

1. Operating system: OS X 10.11.6
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by jesicasaussay** [comment]
issue resolved with
brew install yarn
npm uninstall -g create-react-native-app
yarn global add create-react-native-app

**Comment by cjoshmartin** [comment]
@jesicasaussay soooo do I run yarn start or npm start afterwards... either way it still doesn't work

**Comment by jesicasaussay** [comment]
@cjoshmartin run yarn start. i installed it in a new folder too

**Comment by brentvatne** [comment]
@cjoshmartin - create-react-native-app does not support npm5 currently because npm5 is buggy. you can use npm4 or yarn: https://github.com/react-community/create-react-native-app/issues/233

**Comment by cjoshmartin** [comment]
@jesicasaussay @brentvatne Yes! what I did was downgrade npm and that worked for me

**Comment by nahushf** [comment]
Still facing this Problem:
```
yarn start                                                            
yarn start v0.24.5
$ react-native-scripts start 
10:06:58: Starting packager...
10:07:07: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1039:11
    at Generator.next (<anonymous>)
    at step (/home/nahush/Repos/Packages/WordBank/node_modules/xdl/build/Project.js:1461:191)
    at /home/nahush/Repos/Packages/WordBank/node_modules/xdl/build/Project.js:1461:361
    at <anonymous>
error Command failed with exit code 1.
```

`node -v`: v8.0.0
`npm -v`: v4.6.1
Tried running with npm start as well as yarn start.

Any idea why this could be happening?

**Comment by brentvatne** [comment]
Delete node_modules and run `yarn` again. I imagine you created the project with npm5 installed, and the problem arises when you create and run `npm install` with npm5.

**Comment by alvincrespo** [comment]
Hmm. Running into this issue as well, even though I installed with yarn.

Here is the full history:

```
➜  personal create-react-native-app GardenTracker
Creating a new React Native app in /Users/alvincrespo/workspace/personal/GardenTracker.

Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.27.5
warning ../../../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "xdl@42.0.0" has unmet peer dependency "react@16.0.0-alpha.12".
warning "react-redux@5.0.5" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 316 new dependencies.
├─ @ccheever/crayon@5.0.0
├─ @exponent/json-file@5.3.0
├─ @exponent/ngrok@2.2.7
├─ @exponent/node-auth0@2.6.0
├─ @exponent/osascript@1.6.4
├─ @exponent/spawn-async@1.2.8
├─ @segment/loosely-validate-event@1.1.2
├─ abbrev@1.1.0
├─ accepts@1.3.3
├─ ajv@4.11.8
├─ analytics-node@2.4.1
├─ ansi-escapes@2.0.0
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ any-promise@1.3.0
├─ array-flatten@1.1.1
├─ asap@2.0.5
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ async@0.9.2
├─ asynckit@0.4.0
├─ auth0-js@7.6.1
├─ aws-sign2@0.6.0
├─ aws4@1.6.0
├─ axios@0.16.2
├─ babel-runtime@6.23.0
├─ balanced-match@1.0.0
├─ Base64@0.1.4
├─ base64url@2.0.0
├─ bcrypt-pbkdf@1.0.1
├─ binary@0.3.0
├─ block-stream@0.0.9
├─ bluebird@2.11.0
├─ body-parser@1.17.2
├─ boom@2.10.1
├─ brace-expansion@1.1.8
├─ buffer-equal-constant-time@1.0.1
├─ buffers@0.1.1
├─ bunyan@1.8.10
├─ bytes@2.4.0
├─ callsite@1.0.0
├─ camel-case@1.2.2
├─ caseless@0.12.0
├─ chainsaw@0.1.0
├─ chalk@1.1.3
├─ change-case@2.3.1
├─ cli-cursor@2.1.0
├─ cli-width@2.1.0
├─ clone@2.1.1
├─ co@4.6.0
├─ color-convert@1.9.0
├─ color-name@1.1.2
├─ combined-stream@1.0.5
├─ commander@2.11.0
├─ component-emitter@1.2.1
├─ component-type@1.2.1
├─ concat-map@0.0.1
├─ concat-stream@1.6.0
├─ constant-case@1.1.2
├─ content-disposition@0.5.2
├─ content-type@1.0.2
├─ cookie-signature@1.0.6
├─ cookie@0.3.1
├─ cookiejar@2.1.1
├─ core-js@1.2.7
├─ core-util-is@1.0.2
├─ create-react-class@15.6.0
├─ cross-spawn@5.1.0
├─ cryptiles@2.0.5
├─ crypto-token@1.0.1
├─ dashdash@1.14.1
├─ debug@2.6.7
├─ decache@4.1.0
├─ decompress-zip@0.3.0
├─ deep-diff@0.3.4
├─ delay-async@1.1.0
├─ delayed-stream@1.0.0
├─ depd@1.1.0
├─ destroy@1.0.4
├─ dot-case@1.1.2
├─ dtrace-provider@0.8.3
├─ ecc-jsbn@0.1.1
├─ ecdsa-sig-formatter@1.0.9
├─ ee-first@1.1.1
├─ encodeurl@1.0.1
├─ encoding@0.1.12
├─ es6-error@4.0.2
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ etag@1.8.0
├─ exec-async@2.2.0
├─ exists-async@2.0.0
├─ express@4.15.3
├─ extend@3.0.1
├─ external-editor@2.0.4
├─ extsprintf@1.0.2
├─ fbjs@0.8.12
├─ figures@2.0.0
├─ file-type@4.4.0
├─ finalhandler@1.0.3
├─ follow-redirects@1.2.4
├─ forever-agent@0.6.1
├─ form-data@2.2.0
├─ formidable@1.1.1
├─ forwarded@0.1.0
├─ freeport-async@1.1.1
├─ fresh@0.5.0
├─ fs-extra@3.0.1
├─ fs.realpath@1.0.0
├─ fstream@1.0.11
├─ getpass@0.1.7
├─ glob@7.1.2
├─ graceful-fs@4.1.11
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-color@0.1.7
├─ has-flag@2.0.0
├─ hasbin@1.2.3
├─ hawk@3.1.3
├─ hoek@2.16.3
├─ hoist-non-react-statics@1.2.0
├─ home-dir@1.0.0
├─ http-errors@1.6.1
├─ http-signature@1.1.1
├─ iconv-lite@0.4.15
├─ indent-string@3.1.0
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ inquirer@3.2.0
├─ instapromise@2.0.7-rc.1
├─ invariant@2.2.2
├─ ip@1.1.5
├─ ipaddr.js@1.3.0
├─ is-buffer@1.1.5
├─ is-fullwidth-code-point@2.0.0
├─ is-lower-case@1.1.3
├─ is-promise@2.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ is-upper-case@1.1.2
├─ isarray@1.0.0
├─ isemail@2.2.1
├─ isexe@2.0.0
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ items@2.1.1
├─ joi@10.6.0
├─ join-component@1.1.0
├─ js-tokens@3.0.2
├─ jsbn@0.1.1
├─ jschardet@1.4.2
├─ json-fallback@0.0.1
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.5.1
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsonp@0.0.4
├─ jsonschema@1.1.1
├─ jsonwebtoken@7.4.1
├─ jsprim@1.4.0
├─ jwa@1.1.5
├─ jws@3.1.4
├─ klaw@1.3.1
├─ lock@0.1.3
├─ lodash-es@4.17.4
├─ lodash.once@4.1.1
├─ lodash@4.17.4
├─ loose-envify@1.3.1
├─ lower-case-first@1.0.2
├─ lower-case@1.1.4
├─ lru-cache@4.1.1
├─ match-require@2.1.0
├─ md5hex@1.0.0
├─ media-typer@0.3.0
├─ merge-descriptors@1.0.1
├─ methods@1.1.2
├─ mime-db@1.27.0
├─ mime-types@2.1.15
├─ mime@1.3.4
├─ mimic-fn@1.1.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mkdirp-promise@5.0.1
├─ mkdirp@0.5.1
├─ mkpath@0.1.0
├─ moment@2.18.1
├─ mout@0.11.1
├─ ms@2.0.0
├─ mute-stream@0.0.7
├─ mv@2.1.1
├─ mz@2.6.0
├─ nan@2.6.2
├─ ncp@2.0.0
├─ negotiator@0.6.1
├─ node-fetch@1.7.1
├─ nopt@3.0.6
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object-keys@0.4.0
├─ on-finished@2.3.0
├─ once@1.4.0
├─ onetime@2.0.1
├─ opn@4.0.2
├─ os-tmpdir@1.0.2
├─ param-case@1.1.2
├─ parseurl@1.3.1
├─ pascal-case@1.1.2
├─ path-case@1.1.2
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-to-regexp@0.1.7
├─ performance-now@0.2.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ process-nextick-args@1.0.7
├─ progress@2.0.0
├─ promise-props@1.0.0
├─ promise@7.3.1
├─ prop-types@15.5.10
├─ proxy-addr@1.1.4
├─ pseudomap@1.0.2
├─ punycode@1.3.2
├─ q@1.5.0
├─ qrcode-terminal@0.11.0
├─ qs@6.4.0
├─ querystring@0.2.0
├─ range-parser@1.2.0
├─ raw-body@2.2.0
├─ react-native-scripts@0.0.40
├─ react-redux@5.0.5
├─ read-chunk@2.0.0
├─ readable-stream@2.3.3
├─ redux-logger@2.10.2
├─ redux@3.7.1
├─ regenerator-runtime@0.10.5
├─ remove-trailing-slash@0.1.0
├─ request-progress@3.0.0
├─ request@2.81.0
├─ reqwest@2.0.5
├─ rest-facade@1.5.0
├─ restore-cursor@2.0.0
├─ rimraf@2.6.1
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ safe-buffer@5.1.1
├─ safe-json-stringify@1.0.4
├─ semver@5.3.0
├─ send@0.15.3
├─ sentence-case@1.1.3
├─ serve-static@1.12.3
├─ setimmediate@1.0.5
├─ setprototypeof@1.0.3
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ signal-exit@3.0.2
├─ slugid@1.1.0
├─ slugify@1.1.0
├─ snake-case@1.1.2
├─ sntp@1.0.9
├─ source-map-support@0.4.15
├─ source-map@0.5.6
├─ sshpk@1.13.1
├─ statuses@1.3.1
├─ string_decoder@1.0.3
├─ string-width@2.1.0
├─ stringstream@0.0.5
├─ strip-ansi@4.0.0
├─ superagent-retry@0.6.0
├─ superagent@3.5.2
├─ supports-color@2.0.0
├─ swap-case@1.1.2
├─ symbol-observable@1.0.4
├─ tar.gz@1.0.5
├─ tar@2.2.1
├─ thenify-all@1.6.0
├─ thenify@3.3.0
├─ throttleit@1.0.0
├─ through@2.3.8
├─ title-case@1.1.2
├─ tmp@0.0.31
├─ topo@2.0.2
├─ touch@0.0.3
├─ tough-cookie@2.3.2
├─ traverse@0.3.9
├─ tree-kill@1.1.0
├─ trim@0.0.1
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-is@1.6.15
├─ typedarray@0.0.6
├─ ua-parser-js@0.7.13
├─ universalify@0.1.0
├─ unpipe@1.0.0
├─ upper-case-first@1.1.2
├─ upper-case@1.1.3
├─ url-join@0.0.1
├─ url@0.11.0
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.0
├─ uuid@3.1.0
├─ vary@1.1.1
├─ verror@1.3.6
├─ whatwg-fetch@2.0.3
├─ which@1.2.14
├─ winchan@0.1.4
├─ wrappy@1.0.2
├─ xdl@42.0.0
├─ xhr2@0.1.4
├─ xtend@4.0.1
├─ yallist@2.1.2
└─ yesno@0.0.1
Done in 8.80s.
Installing dependencies using yarnpkg...

yarn install v0.27.5
warning ../../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 12.55s.


Success! Created GardenTracker at /Users/alvincrespo/workspace/personal/GardenTracker
Inside that directory, you can run several commands:

  yarn start
    Starts the development server so you can open your app in the Expo
    app on your phone.

  yarn run ios
    (Mac only, requires Xcode)
    Starts the development server and loads your app in an iOS simulator.

  yarn run android
    (Requires Android build tools)
    Starts the development server and loads your app on a connected Android
    device or emulator.

  yarn test
    Starts the test runner.

  yarn run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd GardenTracker
  yarn start

Happy hacking!
➜  personal cd GardenTracker
➜  GardenTracker yarn start
yarn start v0.27.5
warning ../../../package.json: No license field
$ react-native-scripts start
13:49:01: Starting packager...
***ERROR STARTING PACKAGER***

Error: You are using npm version 5.0.3. Please use an npm version that is >= 3.0.0 and < 5.0.0.
13:49:01: Error starting packager: Error: Couldn't start project. Please fix the errors and restart the project.
    at /xdl/src/Project.js:1038:11
    at Generator.next (<anonymous>)
    at step (/Users/alvincrespo/workspace/personal/GardenTracker/node_modules/xdl/build/Project.js:1468:191)
    at /Users/alvincrespo/workspace/personal/GardenTracker/node_modules/xdl/build/Project.js:1468:361
    at <anonymous>
error Command failed with exit code 1.
➜  GardenTracker
```

Environment:

```
➜  GardenTracker node -v
v8.1.3
➜  GardenTracker npm -v
5.0.3
➜  GardenTracker nvm ls
         v5.3.0
         v6.0.0
         v6.9.1
         v7.2.0
         v7.2.1
         v7.7.2
         v7.8.0
        v7.10.0
         v8.0.0
->       v8.1.3
         system
default -> 7.2.0 (-> v7.2.0)
node -> stable (-> v8.1.3) (default)
stable -> 8.1 (-> v8.1.3) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.3 (-> N/A)
lts/boron -> v6.11.0 (-> N/A)
```

**Comment by pkkalive** [comment]
Guys I am Stuck here I have downgrade both my node and npm 
currently my node version is 8.4.0 and npm is 4.6.1

but create-react-native-app is not working

Purushothams-MacBook-Pro:SampleApp Purushotham$ npm run ios

> SampleApp@0.1.0 ios /Users/Purushotham/Desktop/Demo/SampleApp
> react-native-scripts ios

21:59:37: Starting packager...
21:59:39: Error starting packager: Error: EACCES: permission denied, open '/Users/Purushotham/Desktop/Demo/SampleApp/.expo/packager-info.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SampleApp@0.1.0 ios: `react-native-scripts ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the SampleApp@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Purushotham/.npm/_logs/2017-11-12T16_29_39_085Z-debug.log
