### ISSUE TITLE
could not load exp://ipaddres+port

### ISSUE THREAD

**Issue by antonis80** [react-community/create-react-native-app#81]
I am trying to "npm run android" but on the genymotion emulator i get the above error. Any suggestions please

**Comment by lukaszszymanski** [comment]
Have same problem. It seams that react-native-scripts are running the local server using the first network adapter, in my case ethernet, and i'm running on WiFi. 

Any ideas how to change the default network adapter or change the server address?

**Comment by antonis80** [comment]
same here also, i am running on wifi

**Comment by antonis80** [comment]
Also please check the image for the issue i am facing:

![error](https://cloud.githubusercontent.com/assets/25657046/24055427/9b998d9c-0b48-11e7-8d32-f5cab89c081e.png)

**Comment by dikaiosune** [comment]
@antonis80 are you able to reach http://192.168.0.12:19000 in a web browser on your computer when CRNA is started?

**Comment by antonis80** [comment]
@dikaiosune thank you for the response. i have tried it as you said and i get the following in the browser:

> {"sdkVersion":"14.0.0","name":"logeo","slug":"logeo","version":"0.1.0","xde":true,"developer":{"tool":"crna"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":null},"bundleUrl":"http://192.168.0.12:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"192.168.0.12:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.0.12:19000/logs","id":"@anonymous/logeo-1329440f-f35b-490d-b685-91733bb68359"}

**Comment by dansha** [comment]
almost same for me.
the genymotion android emulator connects but I cannot connect from my android phone (wrong  network).
from: http://192.168.56.1:19000
{"sdkVersion":"14.0.0","name":"testcrna","slug":"testcrna","version":"0.1.0","xde":true,"developer":{"tool":"crna"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":null},"bundleUrl":"http://192.168.56.1:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"192.168.56.1:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.56.1:19000/logs","id":"@anonymous/testcrna-87e2ef63-2232-4d0b-889f-9355e587086e"}

**Comment by dikaiosune** [comment]
@antonis80 @dansha are you both able to get the same result when using your phone's browser?

**Comment by dansha** [comment]
cant access that ip from phone.
both ny PC and the phone are connected to my WIFI but crna is answering a diffrent IP address and not the IP address from the WIFI netwrok.
is there a way to conrtol in what IP the CRNA answers?
here is the result of  ipconfig on my machine:
Windows IP Configuration


Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::ad02:43d2:a9bb:b8ad%7
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::686b:dba8:1317:ca1e%8
   IPv4 Address. . . . . . . . . . . : 192.168.126.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : Home
   Link-local IPv6 Address . . . . . : fe80::850e:77f:81fb:57be%9
   IPv4 Address. . . . . . . . . . . : 10.0.0.7
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.0.138

Tunnel adapter isatap.Home:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : Home

Tunnel adapter Local Area Connection* 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter isatap.{4B394AD1-1A83-4657-B6A3-F2066B2CF54F}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter isatap.{41F61778-411B-476B-82B4-6627C9DAD761}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

**Comment by dikaiosune** [comment]
@dansha I think you should look at https://github.com/react-community/create-react-native-app/issues/60#issuecomment-287081523 for information about how to change the order in which IP addresses appear in ipconfig.

@antonis80 I'll mark this as awaiting-reply until I hear about your network connectivity.

**Comment by antonis80** [comment]
@dikaiosune when i access http://192.168.0.12:19000 from the genymotion emulator browser i get the following error: "the web page at http://192.168.0.12:19000 could not be loaded because: net:ERR_ADDRESS_UNREACHABLE"

My pc network connectivity can be seen below:

`Windows IP Configuration


Wireless LAN adapter Local Area Connection* 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : cablenet.com.cy
   Link-local IPv6 Address . . . . . : fe80::fd7f:e9b8:151c:6004%6
   IPv4 Address. . . . . . . . . . . : 192.168.0.12
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::f8df:7b12:2c45:dea0%13
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::cc22:2b62:950e:28cc%14
   IPv4 Address. . . . . . . . . . . : 192.168.151.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
`

**Comment by dikaiosune** [comment]
@antonis80 can you try following step 1 in this guide? https://docs.expo.io/versions/v15.0.0/guides/genymotion.html

If that does fix things for you, I'll need to add genymotion docs to the user guide.

**Comment by antonis80** [comment]
@dikaiosune i have followed these two steps but still i get the same error. it is really frustrating.

**Comment by antonis80** [comment]
@dansha did you manage to solve it?

**Comment by dansha** [comment]
Yes used #60 to change the order of IPs did the magic

**Comment by antonis80** [comment]
@dasha which one did you give highest priority, wireless or network adapters?

**Comment by dansha** [comment]
My phone was connected via mu WIFI so I gave the wireless the highest
priority so it was first on
ipconfig
in this case CRNA broadcasted with the IP from the WIFI

**Comment by antonis80** [comment]
still nothing on genymotion emulator

**Comment by Sidhanthsur** [comment]
I got the same error . On opening on the browser I got a permission error for state.json inside a .expo folder . I gave it a 777 permission and it started working on my android device.

**Comment by dikaiosune** [comment]
@Sidhanthsur I'm not sure how that's related -- if you still have the error message handy could you open a new issue with that?

@antonis80 what about loading http://localhost:19000 in your emulator's browser? I'm not sure why the emulator isn't able to reach the host network adapter, since we listen on all network interfaces.

**Comment by antonis80** [comment]
@dikaiosune i have tried the http://localhost:19000 and it is reachable, i get the following result in the browser: 
`{"sdkVersion":"14.0.0","name":"logeo","slug":"logeo","version":"0.1.0","xde":true,"developer":{"tool":"crna"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":"i8-q24"},"bundleUrl":"http://192.168.0.12:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"192.168.0.12:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.0.12:19000/logs","id":"@anonymous/logeo-1329440f-f35b-490d-b685-91733bb68359"}`

However i still i get the blue screen when i "npm run android" with the message "could not load exp://ip and port" for both the emulator and the expo app.

**Comment by dikaiosune** [comment]
@antonis80 can you try manually entering `exp://localhost:19000` in the Expo app within the emulator?

**Comment by antonis80** [comment]
@dikaiosune i did not understand your request. The expo app resides on my mobile phone whereas the emulator of genymotion on my computer. Do you mean the expo app's "explore" section?

Thank you for all your support

**Comment by dikaiosune** [comment]
Yeah, if you go to the Explore tab, you can type any URL in the search box, and tap the "attempt to open" button to open it directly.

**Comment by antonis80** [comment]
i just tried it it and i get the same "could not load exp........."

**Comment by antonis80** [comment]
in the error log i get the following: "Uncaught Error: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:19000

**Comment by dikaiosune** [comment]
And you're loading the localhost URL in the Expo app within Genymotion?

**Comment by antonis80** [comment]
i am trying two different methods:
1) running the virtualbox and genymotion emulator + going to the project directory and typing "npm run android" 
2) installed the expo app on my handset, in cmd i run "npm start", then scan the qr code

**Comment by antonis80** [comment]
when i am testing with the expo app i do NOT test with the genymotion emulator, i just close genymotion

**Comment by dikaiosune** [comment]
OK, so, if I'm understanding correctly, there are two scenarios where things aren't working.

The first scenario is inside of a VirtualBox VM, you run `npm run android` with a Genymotion emulator opened. Are you able to run `adb devices` and see the emulator in the list of devices?

The second scenario is when using the Expo app on a physical phone -- are you running the command there inside of the VirtualBox machine, or on the host computer's console?

**Comment by antonis80** [comment]
Yes you are right as concerning the scenarios,  as regards your questions

1. Adb device is working yes

2. I am running on the hos computers console

**Comment by bfreis** [comment]
Hi,

I'm having the same kind of issue with my Android device. I'm using a Google Pixel in a MBP 2016 (the one with just USB-C ports). I've connected my phone to my laptop using an USB-C to A adapter, an USB A cable, and an USB-A to C adapter. Otherwise, ADB (or file transfer) doesn't seem to work (looks like it's a known issue on Google Pixel).

I have created the reverse tunnel with ADB:

    adb reverse tcp:19000 tcp:19000
    adb reverse tcp:19001 tcp:19001

The tunnel (and all that weird cabling!) does work - I open a browser on my Pixel and navigate to http://localhost:19000, it shows the Expo related JSON data.

When I run `yarn run android`, it opens the Expo app on my phone and seems to try to load exp://a-different-ip-address:19000/. This different IP address seem to be my laptop's IP address on the WiFi interface on the network I'm connected to. However, my phone is not (and cannot be) on the same network. That's the reason why I decided to try ADB in the first place.

I then tried to **manually add the exp://127.0.0.1:19000** address to Expo (by the way, terrible UI; I spent 45 minutes looking for a way to manually enter an address in Expo...). Expo still fails to load the app with an error message.

My guess would be that, even though Expo can connect to 127.0.0.0:19000 and download the JSON metadata, that specific metadata seems to be pointing to http://a-different-ip-address:1900. Then Expo is likely trying to connect to that, instead of the IP address I typed.

It seems like the solution would be to change the IP address inside that JSON metadata Expo downloads, but I have no clue on how to do that.

Thanks
Bruno

**Comment by dikaiosune** [comment]
@bfreis thanks -- this makes it much clearer what's happening. I'm working on a solution to resolve this URL mismatch in the manifest server.

**Comment by bfreis** [comment]
@dikaiosune fantastic, thanks!

A nice-to-have would be the ability to somehow configure the IP address I want to use for the IP address in the manifest. Maybe an environment variable? On not-so-trivial network settings on a laptop, might be hard to "guess" the IP address I want/need to use.

Thanks again
Bruno

**Comment by antonis80** [comment]
the only solution i was able to find was the following: 

1) on expo client on my android phone i enabled the wireless hotspot
2) on my pc i have connected to the network using the hotspot of the above mobile device
3) on pc i run "npm start"
4) on mobile handset i open the expo client and scan the qr code generated and the app is oppened

I believe as @dikaiosune said, it is definitely a networking issue, the ip obtained either by the genymotion emulator or the expo client app is different than the one obtained by the react-native commands. I do not know how to match those IPs so as to be on the right track and be able to achieve this without hotspot.

@dikaiosune just a general question, does CRNA support all the features provided by react native? and how to address the react native's components of Android and IOS, do they have common components or API now? For example in react native there is the 'ActionSheetIOS' API.

**Comment by antonis80** [comment]
@dikaiosune when i try "adb devices" while the virtual box+genymotion emulator on my pc is started i get the following:
`C:\Users\User\AndroidStudioProjects\logeo>adb devices
List of devices attached
192.168.151.101:5555    device`

As you can see the ip address of the emulator is different from the one i am shown when i run "npm run android" which is:
` exp://192.168.0.12:19000`

Also this might help you realize the problem. In the virtual Box's command i get the following notification as soon as the genymotion emulator has started: "no such service "dhcpcd-eth0"

**Comment by antonis80** [comment]
@dikaiosune also take into consideration that when testing on real device the pc does not have to be connected via USB to the mobile device as long as they are in the same network. Whenever i perform an update in my code the change is automatically appended to the expo client.

**Comment by dikaiosune** [comment]
@antonis80 you can now specify the IP address to use with the `REACT_NATIVE_PACKAGER_HOSTNAME` environment variable if you upgrade to the newest scripts package (see the user guide) or create a new project.

**Comment by antonis80** [comment]
you are a saver!!!!! thanks

**Comment by antonis80** [comment]
@dikaiosune i created a new project but i can not find the 'REACT_NATIVE_PACKAGER_HOSTNAME' enviroment variable so as to reset it. Where can i find this? Thanks

**Comment by dikaiosune** [comment]
You can set it on the command line like in the user guide, or to make it
permanent there are a bunch of options, I'd recommend Googling for
"$YOUR_OPERATING_SYSTEM environment variables"

Adam Perry

**Comment by antonis80** [comment]
i have tried it in the command line

IN THE COMMAND LINE I TYPE: "REACT_NATIVE_PACKAGER_HOSTNAME='my-custom-ip-address-or-hostname' npm start"

But i  get 'REACT_NATIVE_PACKAGER_HOSTNAME' is not recognized as an internal or external co mmand, operable program or batch file.

Should i set a path in the environment variables of my windows pc?

**Comment by dikaiosune** [comment]
Take a look here:

https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

I think you may need to run `set REACT_NATIVE_PACKAGER_HOSTNAME='something'`. If that works I'll update the user guide for Windows.

**Comment by dikaiosune** [comment]
Also, can you try updating to react-native-scripts 0.0.23 and reinstalling?

Thanks again for all of your help in figuring out how to make this work for users with similar setups to your own.

**Comment by antonis80** [comment]
@dikaiosune ok now crna listens to the specified ip address after setting the environment variable but i get the following error when i try to run npm android:

`Or enter this address in the Expo app's search bar:

  exp://'192.168.151.101' npm start:19000

Your phone will need to be on the same local network as this computer.

For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

Error running adb: Error running app. Error: Activity not started, unable to res
olve Intent { act=android.intent.action.VIEW dat=exp://192.168.151.101 flg=0x100
00000 pkg=npm }`

**Comment by dikaiosune** [comment]
@antonis80 can you also paste the exact command you're running? It looks like the npm start command is getting mixed up in the environment variable you're setting.

**Comment by antonis80** [comment]
@dikaiosune below are the steps i follow:

1) set REACT_NATIVE_PACKAGER_HOSTNAME='192.168.151.101' npm start
2) npm run android OR npm start-> in case i am not using the emulator

Also please note that after i have set the "PACKAGER_HOSTNAME" i always get the following error:

`Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...`

I do not know why this occurred

**Comment by dikaiosune** [comment]
From the docs:

> Windows:
> ```
> set REACT_NATIVE_PACKAGER_HOSTNAME='my-custom-ip-address-or-hostname'
> npm start
> ```

Make sure to set the environment variable on a separate line from running npm start

**Comment by antonis80** [comment]
as regards: `Starting packager... ***ERROR STARTING PACKAGER*** Starting React Native packager...` what is the difference between the "react native packager" and just packager, the 'packager' involves node? 

as regards the issue, now resolved, i really appreciate your help.!! and sorry if a have asked some stupid questions :) 

so, to recap:

1) by setting the HOSTNAME env.variable i have managed to set the IP of CRNA to the one the virtual machine listens to, thus be able to view my app on genymotion emulator. thanks for the patch.
2) i have also managed to view my app on my handset using the QR code ,**ONLY** if the network of my mobile handset is the same as with the computer used to launch CRNA. 

another question to you :) do you have any guide on how to update to react-native-scripts 0.0.23 and reinstalling?

THANKS

**Comment by dikaiosune** [comment]
I'm so glad you were able to get it working! That sounds like a correct summary to me.

There's a small section in the user guide about updating the project's dependencies: https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases

**Comment by zusamann** [comment]
Hi I've just started learning CRNA. I've set it up on my Windows 10 machine and expo app on my android phone. Getting a similar error while trying to connect. I've tried the following three configurations none of which seem to work:

- both laptop and mobile on the same wifi
- mobile on laptop's hotspot
- laptop on mobile's hotspot

Here is my console.
![image](https://cloud.githubusercontent.com/assets/12589797/25020405/cf5780e4-20ab-11e7-9676-ecea494af3b9.png)

I notice the URL seems a bit weird, not 192.xx but 10.0...

Here are my error screens:
![image](https://cloud.githubusercontent.com/assets/12589797/25020511/452847a4-20ac-11e7-9d4c-27805fe6ce30.png)
![image](https://cloud.githubusercontent.com/assets/12589797/25020515/4915ea38-20ac-11e7-8806-75d1c1745832.png)

**Comment by zusamann** [comment]
This is what my IP Config looks like, and clearly the ip is from the hyper-v connection between docker and the system.
```
Windows IP Configuration


Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::6581:de26:5145:be6e%4
   IPv4 Address. . . . . . . . . . . : 10.0.75.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::d47a:9856:1579:3365%6
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::99e4:473c:3fdf:4838%11
   IPv4 Address. . . . . . . . . . . : 192.168.33.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #3:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::bd86:c003:83a2:54a1%7
   IPv4 Address. . . . . . . . . . . : 198.162.10.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 12:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : Home
   Link-local IPv6 Address . . . . . : fe80::456f:7d60:fafb:3efc%10
   IPv4 Address. . . . . . . . . . . : 192.168.1.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.254
                                       192.168.1.1
```

Now when I try Wireless LAN adapter Wi-Fi: IPv4 Address. . . . . . . . . . . : 192.168.1.2 as so
```
set REACT_NATIVE_PACKAGER_HOSTNAME='192.168.1.2'
yarn start
```

The package still starts at the old IP with the `set` command having no effect.

**Comment by zusamann** [comment]
oh my apologies, I forgot that I was using git bash on windows so 
`set REACT_NATIVE_PACKAGER_HOSTNAME='192.168.1.2'` doesn't work, needed to use 
`export REACT_NATIVE_PACKAGER_HOSTNAME="192.168.1.2"`

**Comment by myguidingstar** [comment]
I tried opening the url with browsers and got this error:
```
{"error":"Error: ValidationError: child \"urlRandomness\" fails because [\"urlRandomness\" must be a string]"}
```

**Comment by laromicas** [comment]
I had the same troubles when I was behind a nat, what I did (and worked) was to add port redirects to the firewall for the ports 19000 and 19001.

**Comment by San10694** [comment]
hey ,I am getting same error while running newly created app in Expo client app.I have tried everything nut not getting my application worked on my android mobile.
here is my terminal view
![screenshot 30](https://user-images.githubusercontent.com/23448721/27385936-d0e31662-56b1-11e7-8284-ae55e078bf13.png)

and my react-native dependencies-
 react-native-scripts:--react-native-scripts@0.0.31,
 react-native:-- react-native@0.44.3,
 expo:-- expo@17.0.0,
 node -v:v6.10.1,
 npm -v:3.10.10,
Operating system:windows-10,
Phone/emulator/simulator & version:android v 6.0

 the application is not starting in my headset , I also tried setting set REACT_NATIVE_PACKAGER_HOSTNAME='ip-address'
npm start
but I am not getting things worked each and everytime I am getting same error-"uncaught error:java.net.SocketTimeoutException: failed to connect to /192.168.*.**(port 19000) after 10000ms "

**Comment by charce36** [comment]
For me, the problem was resolved disabled Windows Firewall.

**Comment by DaneGrinder** [comment]
So feel I have tried everything in this and all other threads, but still not working.

I got to the point where:
I can access the address 192.168.0.29:19000 and 19001 from both my android devices browsers and from my PC.

`npm start yields`
Without USB connection the error msg is:
`"Something went wrong. Could not load exp://'192.168.0.29':19000`

The error log:
`Uncaught Error:javaUnknownHostException:Unable to resolve host"'192.168.0.29'": No address associated with hostname`

`npm run android`
With usb connected:
`uncaught Error:Packager is not running at http://'192.168.0.29':19001`

http://192.168.0.29:19000 opened in browser:
`{"sdkVersion":"18.0.0","name":"AwesomeProject","slug":"awesomeproject","version":"0.1.0","xde":true,"developer":{"tool":"crna"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":null},"env":{"REACT_NATIVE_PACKAGER_HOSTNAME":"'192.168.0.29'"},"bundleUrl":"http://'192.168.0.29':19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"'192.168.0.29':19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://'192.168.0.29':19000/logs","id":"@anonymous/awesomeproject-6f531b3f-8197-47dc-9cdc-7ecb8e89f626"}`

http://192.168.0.29:19001 opened in browser:
`React Native packager is running.

Visit documentation`

The console log when visiting http://192.168.0.29:19001 from the phone's browser:
`18:52:29: ::ffff:192.168.0.12 - - [04/Jul/2017:16:52:29 +0000] "GET /favicon.ico HTTP/1.1" 404 24 "http://192.168.0.29:19001/" "Mozilla/5.0 (Linux; Android 7.0; HUAWEI VNS-L31 Build/HUAWEIVNS-L31) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36"`

After running `npm run android` with the usb connected, the AwesomeProject shows up in the EXPO app under recently visited

Spend 3 hours on this now, and just about to go sell the customer on using NativeScript instead :D

Please help..!

**Comment by brentvatne** [comment]
@DaneGrinder - I imagine that you set `REACT_NATIVE_PACKAGER_HOST_NAME` with single quotes around the ip address, see that they show up in this error message:

<img width="553" alt="screen shot 2017-07-04 at 10 26 50" src="https://user-images.githubusercontent.com/90494/27839039-521d7cfe-60a3-11e7-858f-aacb8bf77071.png">

> Spend 3 hours on this now, and just about to go sell the customer on using NativeScript instead :D

Go for it! ;)

**Comment by DaneGrinder** [comment]
They have been showing up like that from the very first time I ran it. I thought it was weird, but then I saw it other threads around the web, so didn't give it any more thought. Didn't set it using quotes last time, but will try it again.

Have tried it, it's the same. It shows up with quotes. Have done from the beginning

**Comment by DaneGrinder** [comment]
Found a hack that "works"

Installed the Expo XDE and changed the settings:
Host: Tunnel -> Lan
Protocol: Exp -> http

Connect the device with USB
Open on Android from Expo XDE

This opens the browser on the phone, put after that I can go into the Expo app and tap "recently visited", and then it works :)

After doing this 1 time, I can change the settings for protocol back to Exp, and now I can launch the project directly from Expo XDE on the phone.

Still no luck from the cli

(Remember to turn off anti-virus and allow access through the firewall)

**Comment by DaneGrinder** [comment]
I do get this warning in Expo XDE, but to tired to go any further with this tonight. A rough 4 hours :)

`Warning: Not using the Expo fork of react-native. See https://docs.expo.io/.`

**Comment by tima-t** [comment]
Solution for windows 10.
Go to cmd and write ipconfig.
Look what is the first Ethernet adapter.
It should be Ethernet adapter Ethernet.
If it is not  and it is something like Ethernet adapter Virtualbox...
Then this is the problem voalaa. Expo is taking the ip adress of the virtualbox.
So go to "Network connections" right click on the adapter you want disable and change the status to disable.
Connect you computer to ethernet and you phone to the same wifi network. 
Restart Expo, then the default url should be changed.
Select host->lan, start the app and then -> run on android.
That's it.

**Comment by mmarovich** [comment]
Soooo... I don't know if this is relevant, but I had this same problem and was able to fix it by switching off my VPN.  Ideally, I'd still like to code with it on, but if I have to turn it off in order to work, no biggie.

**Comment by darentanDZ** [comment]
Disabling Firewall worked. So I guess the problem was with the Firewall settings.

**Comment by OpenKompani** [comment]
Same issues here i have tried everything possible and everything suggestion.  If i can't get t get my code 
 to work how would i trust the framework to build complex apps

**Comment by developdeez** [comment]
I think it's a Windows/Android issue. I tried everything here and it still says "could not load" or "something went wrong". Im just trying to display the blank base project...Maybe Expo isn't fully baked yet.

**Comment by ASAPHAANING** [comment]
I've been experiencing this issue for weeks. Sometimes it works sometimes it doesn't, doesn't matter if I use exp or XDE. I get the right IP & port, i.e.:

[exp] Your URL is

exp://192.168.1.214:19000

But, connecting from the phone will get me either a completely blank page with no loading screen or a red error screen "could not connect to server". Sometimes rebooting fixes this, other days it doesn't matter how much I restart.

OS: Linux x64

**Comment by developdeez** [comment]
Is there a good Web browser preview tool? Expo isn't going to work on sim or phone so we need a stable option.

**Comment by ide** [comment]
The simulator or device are fundamentally going to be far more accurate than a web preview when it comes to the bulk of an app beyond its visuals. Since simulators run on the same device as your computer, you might have fewer issues (especially with the iOS simulator).

**Comment by developdeez** [comment]
This seems to work (for anyone looking):
https://github.com/dabbott/react-native-web-player

**Comment by chiragparekh** [comment]
@tima-t Your solution works perfectly for me.

**Comment by somebrel** [comment]
I had the same issue. Solution? Open the freaking port :see_no_evil:

**Comment by sentinelfm** [comment]
set export REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.2 worked for me. 192.168.1.2 is my IP address

**Comment by dangbh1002** [comment]
Expo and react-devtools conflict!!! If you are using react-devtools, you must uninstall it:
`npm uninstall react-devtools --save-dev`

**Comment by brentvatne** [comment]
@dangbh1002 - that is not true

**Comment by CristhianUNSa** [comment]
This worked for me: I've downloaded adb from android tools then `adb reverse tcp:19000 tcp:19000`, and I didn't put IPv4 address as recommended... my localhost is 127.0.0.1, so manually entering exp://127.0.0.1:19000 in Expo App worked for me. I don't know why is this, just trial and error

**Comment by BarisYazici** [comment]
I had the same problem in macOS Sierra 10.12.16. I changed the firewall options and the problem solved. 
To change it go to System Preferences/Security & Privacy/Firewall Options and "Block all incoming connections" should not be checked.

**Comment by CyrusZei** [comment]
Okay, this might help somebody.

1.Create-react-native.app project name
2.After it says "happy hacking"
3.I use yarn
4.If you run "yarn run ios", you will get the error can't connect to server
5.If you run "yarn start" that will start the dev server
6.then you can press "a" for android and "i" for iPhone
7.done

So hope this help somebody

**Comment by adriancc88** [comment]
Check your firewall settings, try and disable the firewall and run the app to see if it works, if it does just add a custom rule for it.

**Comment by swayampakula** [comment]
Just diable your firewall and if you are trying to do with you laptop then just connect laptop with your router through lan and then connect the mobile through the same wifi and then just try it out it will definitely work.

**Comment by alecperkey** [comment]
similar to other, to get Expo to use the proper hostname i had to change the environmental variable in windows 10. using `set REACT_NATIVE_PACKAGER_HOSTNAME='192.168.1.2' ` did not work

instead:
`setx REACT_NATIVE_PACKAGER_HOSTNAME 192.168.1.2 /M`

where the IP is the IP4 of the WIFI (listed for me last in ipconfig)

**Comment by papadogg** [comment]
Changing REACT_NATIVE_PACKAGER_HOSTNAME and switching off firewall - worked for me

**Comment by vbarinov** [comment]
For windows powershell I used `[Environment]::SetEnvironmentVariable("REACT_NATIVE_PACKAGER_HOSTNAME ", "172.18.1.23", "User")` and restarted the terminal. Check if it is set via `Get-ChildItem Env:`.

**Comment by kowshikm** [comment]
The app is initially running my device after using REACT_NATIVE_PACKAGER_HOSTNAME now i have moved to a different location and my IP address has changed and i have set using the  set REACT_NATIVE_PACKAGER_HOSTNAME=10.10.1.48 and still the app is not working on my mobile

**Comment by Imranjaved2456** [comment]
This is because npm is not hosting your app on the same network, to do that follow these steps : 
1 - run cmd prompt with administrator (win key + x then a => for windows 10 ) 
2- setx REACT_NATIVE_PACKAGER_HOSTNAME 192.168.1.100 /M
NOTE: put ip4 address  above  and you can find your ipv4 address by running command ipconfig on cmd 
PS : If you are connected to a router then reserve your ipv4 address for your MAC address so you will get rid of setting up ip address again and again

**Comment by suhasm1990** [comment]
OMG even i took like 1 and half hour to find why the expo is not loading the app. In home home computer I was able to connect without any issues but in my office, I was unable to connect to expo nor from my browser. The only issue was network type. In my office I somehow had selected it as public network and because of that firewall was blocking it. **Just change the network type to private** and see your app running like a charm :) :) @antonis80

**Comment by Rajas-Git** [comment]
TL;DR; open ports 19000 and 19000.

You need to open ports using Windows Firewall. Open 19000 and also open whatever port (likely 19001) is used in bundleurl when you visit the url in the browser.

**Comment by gregbenner** [comment]
OSX issue still around. Annoying because you can't just ngrok http localhost:19000 to manually override. I'm on the same network, only one adapter: wifi. Firewall off. even tried setting my local ip 192.xx.xxx.xx:19000 the webpage loads but expo fails same as above.

**Comment by brentvatne** [comment]
the problem with running ngrok is that you actually need to do it on two ports in this case: 19000 and 19001 - the first is for the react-native packager and the second is for the manifest/logging server

**Comment by brentvatne** [comment]
additionally, if you want to debug with browser then you need to use a paid version of ngrok in order to support websockets (iirc). you could install exp instead, which gives you ngrok by default. we left this out of CRNA in order for it to not depend on any paid services. to use exp, you can do `npm i -g exp` and then `exp start` and scan the qr code

**Comment by gregbenner** [comment]
@brentvatne I ran into that with ngrok, but the paid version would work with the tls tunnel?
I debugged after all night `npm uninstall react-devtools -g` seemed to fix it, even though react-devtools gui was closed. (Maybe there was a lingering process somewhere.)

**Comment by vishalgadhiya91** [comment]
Please off "Window firewall" and try again

**Comment by gregbenner** [comment]
@vishalgadhiya91 @charce36 already covered this.

**Comment by gitteraz** [comment]
Hi Everyone, i stuck with this for almost 6 hours. After Disabling all the network adapters except my wireless adapter my android mobile started connecting again. 
![image](https://user-images.githubusercontent.com/25010952/33957397-303b31b8-e04a-11e7-854a-2f2822ca1b69.png)

**Comment by zeroFruit** [comment]
@Imranjaved2456 Everytime wifi is changed, this procedure worked like a charm :) thanks!

**Comment by sawangupta** [comment]
Any suggestions for OSX Sierra ? Both Android mobile and Mac are in same WiFi network. No security software running on either of them. However, through mobile I still can't access the http://<MacIP>:19000 url.

**Comment by cbubel** [comment]
I solved an issue like this (on Windows 10) by changing the profile of my home wireless network from Public to Private. Check Network Settings > Change Connection Properties > Network Profile.

**Comment by BWillis98** [comment]
The answers here seem very Windows focused. I'm on Linux 17.10

I have the same issue. It says it's hosted on 192.168.0.6:19000 (where 192.168.0.6 is my IPv4 address) and when I run it says the packager isn't running. I am able to see all of the JSON stuff when I go to 192.168.0.6:19000 from my pc and from my phone.

When I run the command "sudo ufw diable" to disable the firewall and restart the packager, expo says the packager is now hosted on port 80. However, when I try to access 192.168.0.6:80, it's unreachable and I can still access all of the JSON stuff at port 19000. This indicates to me that there's another bug in expo that is telling me the incorrect port it's being hosted on, but I'm not concerned with this bug, because I manually navigated to 192.168.0.6:19000 within expo on my phone and it still gave me the same error that the packager was not running on port 19001. This tells me that the firewall is not the issue.

I've also tried to do: REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.6 and the problem persists.

![image](https://user-images.githubusercontent.com/14190965/34653613-18840e0a-f3b4-11e7-8f6e-3dbc2bacd866.png)

I'm guessing this is the problem somehow (Image above). I'm in serious need of guidance, as I've had this issue for over a week now and it's still not working. It's frustrating and taking time away from my project.

**Comment by BWillis98** [comment]
So, from my computer I can access port 19000 and 19001 and both are working as expected. From my phone, however, I can only access port 19000. 19001 says "This site can't be reached"

**Comment by kurusan** [comment]
For windows disable the firewall and it's good. You can also enable the connection on port 19000.

**Comment by pbandjs** [comment]
I am facing the same issue on macOS Sierra. The XDE says the app is hosted on port 19000 on LAN, but the expo app on android is trying to use port 19001. Did anyone find a fix for this?

**Comment by kurusan** [comment]
Turn off your firewall and retry. It worked for me.

**Comment by piu130** [comment]
I've had the same problem using npm 5. I downgraded it to npm 4 and it worked.

**Comment by kanteankit** [comment]
Hi I am also facing the same issue as @pbandjs . I am using CRNA, yarn and macOS High Sierra.
Before this problem, I was using yarn start to start the packager. The URL it showed was `exp://192.168.1.15:19001`.
Then my wifi went off.So in order to run my app using a USB cable,I ran the following command: `exp start --localhost --android`. This enabled me to run my CRNA app using USB cable.The URL it showed was: `exp://localhost:19000`

But,when my wifi came back and I tried to start the packager using yarn start, then this error message started showing up. Now, I cannot run my app over wifi.

Setting `REACT_NATIVE_PACKAGER_HOSTNAME='192.168.1.15' yarn start` is also not working.
Please help, I cannot find a solution for this.

I don't understand why is this issue closed? People have been commenting on this issue for over a year. The solutions provided are for only Windows. There is no suggestion for MacOS.It should be re-opened again

**Comment by alanlanglois** [comment]
Also got a problem, 
It was working great before I detached, but now it's kind of random.
I got this screen when starting the app : 
![image](https://user-images.githubusercontent.com/712986/36965772-e6ed95d6-205a-11e8-90fa-c80748f67e67.png)
Looks like it's trying to connect to port 80

Here is the exp start powershell: 
![image](https://user-images.githubusercontent.com/712986/36965832-1e93f0ca-205b-11e8-8902-5c95c99389d9.png)

When I try to access it in a browser (in the emulator) : 
![image](https://user-images.githubusercontent.com/712986/36965867-36f61954-205b-11e8-8696-7f1b4fd5793e.png)
![image](https://user-images.githubusercontent.com/712986/36965883-47944cfe-205b-11e8-9d20-58bf70806be9.png)

Seems correct to me, but I can't figured out why my standalone detached app is trying to connect to port 80?

**Comment by brentvatne** [comment]
@jesseruder - any idea why the above error might happen?

**Comment by tingchaoxu** [comment]
I have the same issue on my mac. I change to my iPhone hotspot 'npm run ios' and it works, so I change it back to my wifi and run it again and somehow it fixed and working again.

**Comment by alanlanglois** [comment]
@tingchaoxu Wow, I was skeptical but it actually worked for me... That's really weird, I'll let you know if I loose the connexion again.

**Comment by alanlanglois** [comment]
Still not a perfectly smooth workaround. 
I tried to test using a real device (nexus 5X) and the error was pretty much the same. Both my phone and my laptop are on the same WIFI. 
By trying to make it work on my device, it's not working on the emulator anymore (still try to connect to port 80). 
"Expo start" won't start when connected on my mobile hotspot (maybe the connection is too poor in my office) I'll give it another try at home.

**Comment by jesseruder** [comment]
Not sure why it's trying to connect to port 80. That definitely seems like a bug. @fson any idea why that's happening?

@alanlanglois what's the exact command you're running in powershell to open the app on the emulator?

**Comment by fson** [comment]
Before the XDL server has started, the manifest URL incorrectly points to port 80 (`expoServerPort` is null so the URL uses the default port). Depending on how the detached app gets the URL and the order things happen, this might be happening for the same reason. I have fixed a couple of bugs related to this for the upcoming version of XDL, but still need to check if this particular issue still happens.

Related commits:
https://github.com/expo/xdl/commit/460fedc7044984c01fd80bbb928241a0f351c25b (XDL was requesting localhost:80 to check server status when it was not started yet)
https://github.com/expo/exp/commit/6030333b0d3cc8e36c8efec1189b1143555c55ee (`exp url` retuned an URL with port 80 when server was not started)

**Comment by alanlanglois** [comment]
I've tried all the workaround I found, previously the ip used was the one used by VirtualBox, I finally get it to start on my real wifi IP. 
When I start a build on Android Studio I get this error when exp is started:
![image](https://user-images.githubusercontent.com/712986/37085087-7689b0f4-21f4-11e8-863b-1c77e3c5b108.png)
If I kill Exp and build again, the error is gone and it build succesfully on Android Studio.
Based on @fson comment, I tried this:
- exp start 
- remove the folder "android/support/v7" by myself (via explorer)
- start the build again 
the build work and it connect to port 19000 / 19001. 

It seems to work, fine know, I'll let you know how it goes today :)

Thanks for your help!

**Comment by nsourov** [comment]
Use Expo XDE.
1. Set the Host in "Tunnel"
![1](https://user-images.githubusercontent.com/29119872/37271079-a8041560-25fb-11e8-9ce6-19ed66b78d1a.png)

2. Share the Qr code on your mobile device using Expo mobile app
![2](https://user-images.githubusercontent.com/29119872/37271133-d94401ee-25fb-11e8-9e92-72e6378cbd14.png)

or if you want to run in emulator then select device and choose emulator.
![3](https://user-images.githubusercontent.com/29119872/37271146-e2822722-25fb-11e8-86ae-73ff9b150f87.png)

**Comment by lucaszanella** [comment]
My npm start always starts recommending me exp://VM_IP:80, not 19000. It randomly changes to 19000 after an unknown thing I might be doing. But even when it changes I cannot connect. Only in some rare cases.

I explained it better here. Could somebody help me? :)

https://github.com/react-community/create-react-native-app/issues/602

**Comment by lucaszanella** [comment]
Here's my Dockerfile if somebody wants to know the versions of things I'm installing: https://github.com/lucaszanella/jscam/blob/4982cbfe78685b5241a3a40955fc15f7e25bd631/dev/Dockerfile

**Comment by Symyon** [comment]
Apparently running the packager first and then building the app will switch to the right port.

**Comment by SirPhemmiey** [comment]
Had the same issue. Re-installing the Expo app on my device, and restarting (clear cache) the packager did it. Relieved!

**Comment by lypanov** [comment]
Looks like Windows isn't supported by create-react-native-app. Can't get any of this working either.

**Comment by alvarofernandoms** [comment]
Thanks, @kanteankit!

**Comment by pradoyalle** [comment]
Just do it:
REACT_NATIVE_PACKAGER_HOSTNAME='my-custom-ip-address-or-hostname' 
npm start

**Comment by shemchavez** [comment]
instead of specific IP address given ex **(http://192.168.0.12:19000)**, try **localhost:19000**. Work on my end.

![github01](https://user-images.githubusercontent.com/19364885/41191423-dab0717c-6c21-11e8-9af2-06d2f6ba427c.PNG)

**Comment by boer0327** [comment]
I use genymotion on windows 10. and meet same issues.

I try to turn off firewall fully, and then run yarn run android. everything is work.
So I know this issue cause by firewall issue. but I cannot allow my computer to turn off firewall fully.
I am try to use netstat command "netstat -na |grep 19000" to find all relative port.
Finally, I found three port 6640,6733,19000. and I set them on firewall settings. 

and then everything is work.

**Comment by iddan** [comment]
For me setting REACT_NATIVE_PACKAGER_HOSTNAME to localhost seemed to solve the problem (running a Android emulator on macOS)

**Comment by merbin2012** [comment]
Follow this steps, this should work

1. Goto Control Panel > Network and Internet > Network Connections
2. Right-click the desired connection (Higher Priority Connection)
3. Click Properties > Internet Protocol Version 4
4. Click Properties > Advanced
5. Uncheck 'Automatic Metric'
6. Enter 10 in 'Interface Metric'
7. Click OK

Repeat for the Lower Priority Connection, but this time put 20 into the 'Interface Metric'
You'll now use the higher priority connection as a default.

**Comment by xemran** [comment]
> I am trying to "npm run android" but on the genymotion emulator i get the above error. Any suggestions please

try this command
npx expo install react-native-web@~0.18.9 react-dom@18.1.0 @expo/webpack-config@^0.17.2
